# set verbosity
/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# output path
/Inputs/root_output ./output/xray.root

# initialize run
/run/initialize
/random/setSeeds 0 63

# limit radioactive decay chains
# use if needed
#/grdm/nucleusLimits 1 35 1 17  # aMin aMax zMin zMax

# particle type
# e-, e+, mu-, mu+, neutron, proton, anti_proton, pi-, pi+, pi0, kaon-, kaon+,
# gamma, opticalphoton, ...
/gps/particle gamma

# rectangular plane source
# 480 cm × 80 cm xz plane at y=100 cm
/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 1 0
/gps/pos/centre 0. 0. -5. cm
/gps/pos/halfx 1. cm
/gps/pos/halfy 1. cm

# angular distribution
# initial momentum in the -y direction
/gps/ang/type iso
/gps/ang/rot1 1 0 0
/gps/ang/rot2 0 -1 0
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 0 deg  # opening angle of cone

# energy distribution
/gps/ene/type Mono
/gps/ene/mono 0.45 MeV
/gps/ene/sigma 0.35 MeV

# run
/run/beamOn 100000
